### ISSUE TITLE
[mongoose-transactions-typescript]: TypeError: mongoose_transactions_typescript_1.default is not a constructor

### ISSUE THREAD

**Issue by Nongfsq** [daton89-topperblues/mongoose-transactions#20]
const transaction = new mongoose_transactions_typescript_1.default();
                    ^

TypeError: mongoose_transactions_typescript_1.default is not a constructor
    at Object.<anonymous> (E:\Project\WorkProject\backend\dist\service\wallet.service.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)    
    at Object.<anonymous> (E:\Project\WorkProject\backend\dist\routes\wallet.js:6:26)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)    
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! backend@1.0.0 start: `rm -rf dist && tsc & node ./dist/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the backend@1.0.0 start script.        
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by daton89** [comment]
Please provide more information about your environment and a sample of the code you are trying to run!
