### ISSUE TITLE
MissingSchemaError: Schema hasn't been registered for model

### ISSUE THREAD

**Issue by ngocvietlala** [daton89-topperblues/mongoose-transactions#9]
Hi guys. I am new on mongoose, after googling i found this plugin and i want to add this plugin to my PJ but somehow i got this error when try to insert to my db. This error only occur when i try to use with this plugin, i was checked my mongoose instance and it has schema but plugin keep throw this error....

This is my mongoose model schema: 
`modelSchemas:
      { Room: [Schema] },`

and the code i was used is :
`try {
const product = request.headers.product;
const newRooms = request.payload.new_rooms;
newRooms.forEach(val => {
val.product = product;
transaction.insert('Room', val);
});
const final = await transaction.run();
return final;
} catch (e) {
console.error(e);
const rollbackObj = await transaction.rollback().catch(console.error);
transaction.clean()
}`

**Comment by topperblues** [comment]
Hi,
you need to define mongoose schema and model and then use them in transaction.
So, if i understand your problem, your code must be something like this:
```   
//First of all, define your mongoose schema and model somewhere in your project
var mongoose = require('mongoose');   
var Schema = mongoose.Schema;   
// Create schema   
var RoomSchema = new Schema({   
    //Your room field definition here   
   // See http://mongoosejs.com/docs/guide.html   
  });   
//Create model   
var Room = mongoose.model('Room', RoomSchema);   

...   

//Then use it in transaction   
transaction.insert('Room', val);   

...   
```
This solve your problem?
I answer your question?
Regards

**Comment by ngocvietlala** [comment]
Yes. But i separated them in to 3 file like IOC pattern. 
- First file is model it just define Room Model with it schema then export it.
- Second file is the repository for Room Model. ( i import the Room model )
- Last file is controller which place that handle the request.
I want to use your plugin in my RoomController file. So in my controller look like this:
const RoomRepo = require(....'room.repo.js');
const Transaction = required('mongooses-transaction');
Transaction = new transaction();
and in controller i call it like this but it throw Schema not found error.
Transaction.insert('Room', val);

**Comment by daton89** [comment]
Hi @ngocvietlala,

are you sure that in your room.repo after you create your schema you compile it to register the model?  
as @topperblues explained before these two operations are required.

```
// ROOM REPO
// create schema
var RoomSchema = new Schema({   
    name: String
});   

// Compile schema and register the model   
var Room = mongoose.model('Room', RoomSchema);   

// then you can export the model and the schema or only the one that you need
module.exports = {
  schema: RoomSchema,
  model: Room
}
```

now when you do:
```
const RoomRepo = require(....'room.repo.js');
const Transaction = required('mongooses-transaction');
Transaction = new transaction();
Transaction.insert('Room', val);
```

it should work

**Comment by ngocvietlala** [comment]
Thank you very much @topperblues and @daton89 . I ll check it when i come back home tonight and will feedback to you.

**Comment by ngocvietlala** [comment]
Hi @daton89 .
I just try your solution but i seems not work on me. I don't know why then i try switch to just 2 file model and controller but it not work too.

This is my model file:
```javascript
const mongoose = require('mongoose');
const autoIncrement = require('mongoose-plugin-autoinc');
const mongoose_delete = require('mongoose-delete');
mongoose.Promise = global.Promise;

const Schema = mongoose.Schema;

const roomSchema = mongoose.Schema({
    name: {
        type: String,
        required: true
    },
    created_at: {type: Date, default: Date.now()},
    updated_at: {type: Date, default: Date.now()},
}, {toJSON: {virtuals: true}, toObject: {virtuals: true}});

roomSchema.plugin(autoIncrement.plugin, { model: 'Room', field: 'room_index' });
roomSchema.plugin(mongoose_delete, {deletedAt: true, deletedBy: true});

const Room = mongoose.model('Room', roomSchema);

module.exports = {
    schema: roomSchema,
    model: Room
};
``` 

And this is controller file:

```javascript
const Room = require('../model/room');
const Transaction = require('mongoose-transactions');
module.exports = [
    {
        method: 'POST',
        path: '/room',
        options: {
            auth: 'jwt',
            validate: {
                payload: {
                    name: Joi.string().required(),
                }
            },
            handler: async (request, h) => {
                const params = {
                    name: request.payload.name,
                };
                try {
                    const transaction = new Transaction();
                    const id = transaction.insert('Room', params);
                    return await transaction.run();
                } catch (error) {
                    console.error(error);
                    const rollbackObj = await transaction.rollback().catch(console.error);
                    transaction.clean()
                }
            }
        }
    }
},
```


The error is: { MissingSchemaError: Schema hasn't been registered for model "Room".
Use mongoose.model(name, schema)
P/s sorry i don't know how to place code nice like you guys....

**Comment by daton89** [comment]
@ngocvietlala 
the controller is the unique file where you import your model? 
which version of node, mongo and mongoose are you using?
can you show your error?

**Comment by ngocvietlala** [comment]
@daton89 
this is full version of error.
```javascript
Server running at: http://localhost:3000
Mongoose connected
Mongoose {
  connections:
   [ NativeConnection {
       base: [Circular],
       collections: [Object],
       models: [Object],
       config: [Object],
       replica: false,
       hosts: null,
       host: null,
       port: null,
       user: null,
       pass: null,
       name: null,
       options: null,
       otherDbs: [],
       states: [Object],
       _readyState: 0,
       _closeCalled: false,
       _hasOpened: false,
       _listening: false } ],
  models:
   { MongooseTransactions:
      { [Function: model]
        hooks: [Kareem],
        base: [Circular],
        modelName: 'MongooseTransactions',
        model: [Function: model],
        db: [NativeConnection],
        discriminators: undefined,
        '$appliedMethods': true,
        '$appliedHooks': true,
        _events: [Object],
        _eventsCount: 2,
        schema: [Schema],
        collection: [NativeCollection],
        Query: [Function],
        '$__insertMany': [Function],
        insertMany: [Function],
        '$init': [Promise] } },
  modelSchemas:
   { MongooseTransactions:
      Schema {
        obj: [Object],
        paths: [Object],
        aliases: {},
        subpaths: {},
        virtuals: [Object],
        singleNestedPaths: {},
        nested: {},
        inherits: {},
        callQueue: [Array],
        _indexes: [],
        methods: {},
        statics: {},
        tree: [Object],
        query: {},
        childSchemas: [],
        plugins: [Array],
        s: [Object],
        _userProvidedOptions: undefined,
        options: [Object],
        '$globalPluginsApplied': true } },
  options: { pluralization: true },
  plugins:
   [ [ [Function], [Object] ],
     [ [Function], [Object] ],
     [ [Function], [Object] ] ] }
Room
{ MissingSchemaError: Schema hasn't been registered for model "Room".
Use mongoose.model(name, schema)
    at new MissingSchemaError (/mnt/c/workspace/myappserver/node_modules/mongoose-transactions/node_modules/mongoose/lib/error/missingSchema.js:20:11)
    at Mongoose.model (/mnt/c/workspace/myappserver/node_modules/mongoose-transactions/node_modules/mongoose/lib/index.js:391:13)
    at Transaction.insert (/mnt/c/workspace/myappserver/node_modules/mongoose-transactions/dist/src/main.js:219:30)
    at handler (/mnt/c/workspace/myappserver/src/controller/room.controller.js:26:44)
    at module.exports.internals.Manager.execute (/mnt/c/workspace/myappserver/node_modules/hapi/lib/toolkit.js:35:106)
    at Object.internals.handler (/mnt/c/workspace/myappserver/node_modules/hapi/lib/handler.js:52:48)
    at exports.execute (/mnt/c/workspace/myappserver/node_modules/hapi/lib/handler.js:37:36)
    at module.exports.internals.Request._lifecycle (/mnt/c/workspace/myappserver/node_modules/hapi/lib/request.js:261:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  message: 'Schema hasn\'t been registered for model "Room".\nUse mongoose.model(name, schema)',
  name: 'MissingSchemaError' }
Debug: internal, implementation, error
    ReferenceError: transaction is not defined
    at handler (/mnt/c/workspace/myappserver/src/controller/room.controller.js:31:41)
    at module.exports.internals.Manager.execute (/mnt/c/workspace/myappserver/node_modules/hapi/lib/toolkit.js:35:106)
    at Object.internals.handler (/mnt/c/workspace/myappserver/node_modules/hapi/lib/handler.js:52:48)
    at exports.execute (/mnt/c/workspace/myappserver/node_modules/hapi/lib/handler.js:37:36)
    at module.exports.internals.Request._lifecycle (/mnt/c/workspace/myappserver/node_modules/hapi/lib/request.js:261:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

P/s i using Hapijs-v17 and node v9.3.0, mongoose ^5.0.12 and mongo 3.4 i think

**Comment by daton89** [comment]
@ngocvietlala 
i'm not expert of the lifecycle of a controller in hapi.js 
i don't know if this problem is related to the transaction module..
can you try this?

```
// model file 
roomSchema.plugin(autoIncrement.plugin, { model: 'Room', field: 'room_index' });
roomSchema.plugin(mongoose_delete, {deletedAt: true, deletedBy: true});

// add console log
console.log('ready to compile model')

const Room = mongoose.model('Room', roomSchema);

module.exports = {
    schema: roomSchema,
    model: Room
};

// controller file 

handler: async (request, h) => {
   const params = {
     name: request.payload.name,
     floor: request.payload.floor,
     product: request.headers.product
  };
  // move declaration of transaction before the try couse in the catch transaction will be not defined
  let transaction;
  try {
     transaction = new Transaction();
     // add console log
     console.log('ready to fire transaction insert');
     const id = transaction.insert('Room', params);
     return await transaction.run();
   } catch (error) {
      console.error(error);
       const rollbackObj = await transaction.rollback().catch(console.error);
       transaction.clean()
   }
}
```

can you show me the coonsole output?

**Comment by ngocvietlala** [comment]
@daton89 
yes i try and the result is the same error.
My model file:
```javascript
const mongoose = require('mongoose');
const autoIncrement = require('mongoose-plugin-autoinc');
const mongoose_delete = require('mongoose-delete');
mongoose.Promise = global.Promise;

const Schema = mongoose.Schema;

const roomSchema = mongoose.Schema({
    name: {
        type: String,
        required: true
    },
    created_at: {type: Date, default: Date.now()},
    updated_at: {type: Date, default: Date.now()},
}, {toJSON: {virtuals: true}, toObject: {virtuals: true}});

roomSchema.plugin(autoIncrement.plugin, { model: 'Room', field: 'room_index' });
roomSchema.plugin(mongoose_delete, {deletedAt: true, deletedBy: true});

const Room = mongoose.model('Room', roomSchema);

module.exports = {
    schema: roomSchema,
    model: Room
};
```

And this is my controller:
```javascript
const Room = require('../model/room');
const Transaction = require('mongoose-transactions');
const Joi = require('joi');

module.exports = [
    {
        method: 'POST',
        path: '/room',
        options: {
            auth: 'jwt',
            validate: {
                payload: {
                    name: Joi.string().required(),
                }
            },
            handler: async (request, h) => {
                const params = {
                    name: request.payload.name,
                };
                let transaction;
                try {
                    transaction = new Transaction();
                    // add console log
                    console.log('ready to fire transaction insert');
                    const id = transaction.insert('Room', params);
                    return await transaction.run();
                } catch (error) {
                    console.error(error);
                    const rollbackObj = await transaction.rollback().catch(console.error);
                    transaction.clean()
                }
            }
        },

    },
```

and this is full error in console:
```javascript
Server running at: http://localhost:3000
Mongoose connected
ready to fire transaction insert
Mongoose {
  connections:
   [ NativeConnection {
       base: [Circular],
       collections: [Object],
       models: [Object],
       config: [Object],
       replica: false,
       hosts: null,
       host: null,
       port: null,
       user: null,
       pass: null,
       name: null,
       options: null,
       otherDbs: [],
       states: [Object],
       _readyState: 0,
       _closeCalled: false,
       _hasOpened: false,
       _listening: false } ],
  models:
   { MongooseTransactions:
      { [Function: model]
        hooks: [Kareem],
        base: [Circular],
        modelName: 'MongooseTransactions',
        model: [Function: model],
        db: [NativeConnection],
        discriminators: undefined,
        '$appliedMethods': true,
        '$appliedHooks': true,
        _events: [Object],
        _eventsCount: 2,
        schema: [Schema],
        collection: [NativeCollection],
        Query: [Function],
        '$__insertMany': [Function],
        insertMany: [Function],
        '$init': [Promise] } },
  modelSchemas:
   { MongooseTransactions:
      Schema {
        obj: [Object],
        paths: [Object],
        aliases: {},
        subpaths: {},
        virtuals: [Object],
        singleNestedPaths: {},
        nested: {},
        inherits: {},
        callQueue: [Array],
        _indexes: [],
        methods: {},
        statics: {},
        tree: [Object],
        query: {},
        childSchemas: [],
        plugins: [Array],
        s: [Object],
        _userProvidedOptions: undefined,
        options: [Object],
        '$globalPluginsApplied': true } },
  options: { pluralization: true },
  plugins:
   [ [ [Function], [Object] ],
     [ [Function], [Object] ],
     [ [Function], [Object] ] ] }
Room
{ MissingSchemaError: Schema hasn't been registered for model "Room".
Use mongoose.model(name, schema)
    at new MissingSchemaError (/mnt/c/workspace/myappserver/node_modules/mongoose-transactions/node_modules/mongoose/lib/error/missingSchema.js:20:11)
    at Mongoose.model (/mnt/c/workspace/myappserver/node_modules/mongoose-transactions/node_modules/mongoose/lib/index.js:391:13)
    at Transaction.insert (/mnt/c/workspace/myappserver/node_modules/mongoose-transactions/dist/src/main.js:219:30)
    at handler (/mnt/c/workspace/myappserver/src/controller/room.controller.js:26:44)
    at module.exports.internals.Manager.execute (/mnt/c/workspace/myappserver/node_modules/hapi/lib/toolkit.js:35:106)
    at Object.internals.handler (/mnt/c/workspace/myappserver/node_modules/hapi/lib/handler.js:52:48)
    at exports.execute (/mnt/c/workspace/myappserver/node_modules/hapi/lib/handler.js:37:36)
    at module.exports.internals.Request._lifecycle (/mnt/c/workspace/myappserver/node_modules/hapi/lib/request.js:261:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  message: 'Schema hasn\'t been registered for model "Room".\nUse mongoose.model(name, schema)',
  name: 'MissingSchemaError' }
Debug: internal, implementation, error
    Error: handler method did not return a value, a promise, or throw an error
    at module.exports.internals.Manager.execute (/mnt/c/workspace/myappserver/node_modules/hapi/lib/toolkit.js:52:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

This error not happen when i use with another method some thing like:
```javascript
Room.find({_id: 'foooo});
```
the result of this is that room.

**Comment by daton89** [comment]
you missed to add the console log in your model

```
// model file 
roomSchema.plugin(autoIncrement.plugin, { model: 'Room', field: 'room_index' });
roomSchema.plugin(mongoose_delete, {deletedAt: true, deletedBy: true});

// add console log
console.log('ready to compile model')

const Room = mongoose.model('Room', roomSchema);

module.exports = {
    schema: roomSchema,
    model: Room
};

```

log?

**Comment by ngocvietlala** [comment]
Oh Sorry @daton89 i update the log.
```javascript
[nodemon] restarting due to changes...
[nodemon] starting `node src/app.js`
ready to compile model
Server running at: http://localhost:3000
Mongoose connected
ready to fire transaction insert
Mongoose {
  connections:
   [ NativeConnection {
       base: [Circular],
       collections: [Object],
       models: [Object],
       config: [Object],
       replica: false,
       hosts: null,
       host: null,
       port: null,
       user: null,
       pass: null,
       name: null,
       options: null,
       otherDbs: [],
       states: [Object],
       _readyState: 0,
       _closeCalled: false,
       _hasOpened: false,
       _listening: false } ],
  models:
   { MongooseTransactions:
      { [Function: model]
        hooks: [Kareem],
        base: [Circular],
        modelName: 'MongooseTransactions',
        model: [Function: model],
        db: [NativeConnection],
        discriminators: undefined,
        '$appliedMethods': true,
        '$appliedHooks': true,
        _events: [Object],
        _eventsCount: 2,
        schema: [Schema],
        collection: [NativeCollection],
        Query: [Function],
        '$__insertMany': [Function],
        insertMany: [Function],
        '$init': [Promise] } },
  modelSchemas:
   { MongooseTransactions:
      Schema {
        obj: [Object],
        paths: [Object],
        aliases: {},
        subpaths: {},
        virtuals: [Object],
        singleNestedPaths: {},
        nested: {},
        inherits: {},
        callQueue: [Array],
        _indexes: [],
        methods: {},
        statics: {},
        tree: [Object],
        query: {},
        childSchemas: [],
        plugins: [Array],
        s: [Object],
        _userProvidedOptions: undefined,
        options: [Object],
        '$globalPluginsApplied': true } },
  options: { pluralization: true },
  plugins:
   [ [ [Function], [Object] ],
     [ [Function], [Object] ],
     [ [Function], [Object] ] ] }
Room
{ MissingSchemaError: Schema hasn't been registered for model "Room".
Use mongoose.model(name, schema)
    at new MissingSchemaError (/mnt/c/workspace/myappserver/node_modules/mongoose-transactions/node_modules/mongoose/lib/error/missingSchema.js:20:11)
    at Mongoose.model (/mnt/c/workspace/myappserver/node_modules/mongoose-transactions/node_modules/mongoose/lib/index.js:391:13)
    at Transaction.insert (/mnt/c/workspace/myappserver/node_modules/mongoose-transactions/dist/src/main.js:219:30)
    at handler (/mnt/c/workspace/myappserver/src/controller/room.controller.js:25:44)
    at module.exports.internals.Manager.execute (/mnt/c/workspace/myappserver/node_modules/hapi/lib/toolkit.js:35:106)
    at Object.internals.handler (/mnt/c/workspace/myappserver/node_modules/hapi/lib/handler.js:52:48)
    at exports.execute (/mnt/c/workspace/myappserver/node_modules/hapi/lib/handler.js:37:36)
    at module.exports.internals.Request._lifecycle (/mnt/c/workspace/myappserver/node_modules/hapi/lib/request.js:261:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  message: 'Schema hasn\'t been registered for model "Room".\nUse mongoose.model(name, schema)',
  name: 'MissingSchemaError' }
Debug: internal, implementation, error
    Error: handler method did not return a value, a promise, or throw an error
    at module.exports.internals.Manager.execute (/mnt/c/workspace/myappserver/node_modules/hapi/lib/toolkit.js:52:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by daton89** [comment]
ok...
can you now replace your handler like this

```
            handler: async (request, h) => {
                const params = {
                    name: request.payload.name,
                    floor: request.payload.floor,
                    product: request.headers.product
                };
                try {
                    return await Room.model.find({});
                } catch (error) {
                    console.error(error);
                }
            }
```
it works?
if it works can you show me you mongoose connection configuration?

**Comment by ngocvietlala** [comment]
@daton89 
Yes it works.
```javascript
[
    {
        "created_at": "2018-04-03T14:34:01.686Z",
        "updated_at": "2018-04-14T08:12:42.911Z",
        "deleted": false,
        "_id": "5ac3936105e98200deb5fac5",
        "room_index": 0,
        "name": "101",
        "floor": "5ac3926005e98200deb5fabd",
        "product": "5a576be0e9d76e012ddb8893",
        "__v": 0,
        "room_type": "5abf91d91442b40200927278",
        "id": "5ac3936105e98200deb5fac5"
    },
.........
]
```

**Comment by daton89** [comment]
can you show me you mongoose connection configuration?

**Comment by ngocvietlala** [comment]
@daton89 
Yes this is mongoose connection configuration.
```javascript
const Path = require('path');
const Hapi = require('hapi');
const mongoose = require('mongoose');
const dotenv = require('dotenv');
dotenv.config();
mongoose.connect(process.env.DATABASE).then(() => {
    console.log('Mongoose connected');
}).catch((err) => console.log(err));
mongoose.Promise = global.Promise;
```

**Comment by daton89** [comment]
can you try this please?

```
handler: async (request, h) => {
    const params = {
        name: request.payload.name,
        floor: request.payload.floor,
        product: request.headers.product
    };
    try {
        const Model = mongoose.model('Room')
        return await Model.find({});
    } catch (error) {
        console.error(error);
    }
}
```

**Comment by ngocvietlala** [comment]
@daton89 
yes it works if i define
```javascript
const mongoose = require('mongoose');
```

**Comment by daton89** [comment]
what version of node, mongodb, mongoose are you using?

**Comment by ngocvietlala** [comment]
@daton89 
i using node v9.3.0, mongodb 3.4, i was try this plugin when i using mongoose 4.3 and it not work. I just update mongoose to ^5.0.12

**Comment by daton89** [comment]
can you try using mongoose 4.11?

**Comment by ngocvietlala** [comment]
@daton89 
i down mongoose to 4.11.0 and it still error. This is the error.
```javascript
[nodemon] 1.17.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node src/app.js`
(node:24676) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`
(node:24676) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
Server running at: http://localhost:3000
Mongoose connected
{ MissingSchemaError: Schema hasn't been registered for model "Room".
Use mongoose.model(name, schema)
    at new MissingSchemaError (/home/neolab/Documents/projects/myappserver/node_modules/mongoose-transactions/node_modules/mongoose/lib/error/missingSchema.js:20:11)
    at Mongoose.model (/home/neolab/Documents/projects/myappserver/node_modules/mongoose-transactions/node_modules/mongoose/lib/index.js:391:13)
    at Transaction.insert (/home/neolab/Documents/projects/myappserver/node_modules/mongoose-transactions/dist/src/main.js:218:30)
    at handler (/home/neolab/Documents/projects/myappserver/src/controller/room.controller.js:24:33)
    at module.exports.internals.Manager.execute (/home/neolab/Documents/projects/myappserver/node_modules/hapi/lib/toolkit.js:35:106)
    at Object.internals.handler (/home/neolab/Documents/projects/myappserver/node_modules/hapi/lib/handler.js:52:48)
    at exports.execute (/home/neolab/Documents/projects/myappserver/node_modules/hapi/lib/handler.js:37:36)
    at module.exports.internals.Request._lifecycle (/home/neolab/Documents/projects/myappserver/node_modules/hapi/lib/request.js:261:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  message: 'Schema hasn\'t been registered for model "Room".\nUse mongoose.model(name, schema)',
  name: 'MissingSchemaError' }
Debug: internal, implementation, error 
    Error: handler method did not return a value, a promise, or throw an error
    at module.exports.internals.Manager.execute (/home/neolab/Documents/projects/myappserver/node_modules/hapi/lib/toolkit.js:52:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)

```

**Comment by daton89** [comment]
do you have mongoose and mongoose-transactions in your dependencies in package.json?

**Comment by ngocvietlala** [comment]
@daton89 
Yes i do. In my package.json:
-   "mongoose-transactions": "^1.1.0" is my current version in dependencies.

**Comment by daton89** [comment]
@ngocvietlala 
ok i think that i found the problem... i've updated the module... now latest version is 1.1.1
try run: `npm uninstall mongoose-transactions -S && npm install mongoose-transactions -S`
is it fixed now?

**Comment by ngocvietlala** [comment]
@daton89 
Thank you very much. I will check if when i comeback home to night and feedback to you.

**Comment by ngocvietlala** [comment]
@daton89 
Thank you very much. It works now.
